plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/mariagarcia/Desktop/EARLY/Outil LISTES/V_180226/fonts"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]